# This is a workflow to deploy the latest code from the asn1js rease branch
name: asn1js release workflow

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: asn1js release deployment
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
    - uses: actions/checkout@v4

    # change to the asn1 directory
    - name: change directory
      run: cd asn1js
    - name: cleanup directory
      run: rm -rf *

    - name: download latest asn1js release
      run: curl -L https://github.com/olibu/asn1js/archive/release.tar.gz | tar zxf -

    - name: move content to the right place
      run: mv asn1js-release/* ./

    - name: cleanup extraced archive folder
      run: rm -rf asn1js-release

    - name: show directory
      run: ls -l

    # Commit and push all changed files.
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "cicd@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
